--DROP TABLES

DROP TABLE PROJETO.EMPRESTIMO;
DROP TABLE PROJETO.LIVRO;
DROP TABLE PROJETO.USUARIO;
DROP TABLE PROJETO.TIPO_USUARIO;
DROP TABLE PROJETO.AUTOR;

--DROP SCHEMA

DROP SCHEMA PROJETO RESTRICT;

--CREATE SCHEMA

CREATE SCHEMA PROJETO;

--CREATE TABLES

CREATE TABLE PROJETO.LIVRO
(
ID_LIVRO INTEGER NOT NULL PRIMARY KEY GENERATED always AS IDENTITY (START WITH 1, increment BY 1),
ID_AUTOR INTEGER NOT NULL, 
NOME_LIVRO VARCHAR(100) NOT NULL
);

CREATE TABLE PROJETO.USUARIO
( 
ID_USUARIO INTEGER NOT NULL PRIMARY KEY GENERATED always AS IDENTITY (START WITH 1, increment BY 1), 
NOME_USUARIO VARCHAR(100) NOT NULL,
LOGIN_USUARIO VARCHAR(15) NOT NULL,
SENHA_USUARIO VARCHAR(32) NOT NULL,
ID_TIPO_USUARIO INTEGER NOT NULL
);

CREATE TABLE PROJETO.TIPO_USUARIO
(
ID_TIPO_USUARIO INTEGER NOT NULL PRIMARY KEY GENERATED always AS IDENTITY (START WITH 1, increment BY 1),
NOME_TIPO_USUARIO VARCHAR(100) NOT NULL
);

CREATE TABLE PROJETO.AUTOR
( 
ID_AUTOR INTEGER NOT NULL PRIMARY KEY GENERATED always AS IDENTITY (START WITH 1, INCREMENT BY 1),
NOME_AUTOR VARCHAR(100) NOT NULL
);

CREATE TABLE PROJETO.EMPRESTIMO
( 
ID_EMPRESTIMO INTEGER NOT NULL PRIMARY KEY GENERATED always AS IDENTITY (START WITH 1, INCREMENT BY 1),
ID_LIVRO INTEGER NOT NULL,
ID_USUARIO INTEGER NOT NULL, 
DATA_EMPRESTIMO DATE NOT NULL
);

--ALTER TABLE LIGAÇÃO DE OBRA E AUTOR

ALTER TABLE PROJETO.LIVRO
ADD FOREIGN KEY (ID_AUTOR)
REFERENCES PROJETO.AUTOR(ID_AUTOR)
ON DELETE CASCADE;

--ALTER TABLE LIGAÇÃO DE EMPRESTIMO E OBRA

ALTER TABLE PROJETO.EMPRESTIMO
ADD FOREIGN KEY (ID_LIVRO)
REFERENCES PROJETO.LIVRO(ID_LIVRO)
ON DELETE CASCADE;

--ALTER TABLE LIGAÇÃO DE EMPRESTIMO E USUARIO

ALTER TABLE PROJETO.EMPRESTIMO
ADD FOREIGN KEY (ID_USUARIO)
REFERENCES PROJETO.USUARIO(ID_USUARIO)
ON DELETE CASCADE;

--ALTER TABLE LIGAÇÃO DE USUARIO E TIPO DE USUARIO

ALTER TABLE PROJETO.USUARIO
ADD FOREIGN KEY (ID_TIPO_USUARIO)
REFERENCES PROJETO.TIPO_USUARIO(ID_TIPO_USUARIO)
ON DELETE CASCADE;

--INSERT AUTOR

INSERT
INTO PROJETO.AUTOR(NOME_AUTOR)
VALUES('Arthur Conan Doyle');

INSERT
INTO PROJETO.AUTOR(NOME_AUTOR)
VALUES('Stephen King');

INSERT
INTO PROJETO.AUTOR(NOME_AUTOR)
VALUES('Paulo Coelho');

INSERT
INTO PROJETO.AUTOR(NOME_AUTOR)
VALUES('Bernard Cornwell');

INSERT
INTO PROJETO.AUTOR(NOME_AUTOR)
VALUES('H.P. Lovecraft');

INSERT
INTO PROJETO.AUTOR(NOME_AUTOR)
VALUES('Isaac Asimov');

--INSERT TIPO DE USUÁRIO

INSERT
INTO PROJETO.TIPO_USUARIO(NOME_TIPO_USUARIO)
VALUES('Usuário Normal');

INSERT
INTO PROJETO.TIPO_USUARIO(NOME_TIPO_USUARIO)
VALUES('Admin');

--INSERT USUÁRIO

INSERT
INTO PROJETO.USUARIO(NOME_USUARIO, LOGIN_USUARIO, SENHA_USUARIO, ID_TIPO_USUARIO)
VALUES('Valdemar de Melo Neves Junior','vmnevesjr','123456',1);

INSERT
INTO PROJETO.USUARIO(NOME_USUARIO, LOGIN_USUARIO, SENHA_USUARIO, ID_TIPO_USUARIO)
VALUES('Patrick Gainher','patgainher','123456',1);

INSERT
INTO PROJETO.USUARIO(NOME_USUARIO, LOGIN_USUARIO, SENHA_USUARIO, ID_TIPO_USUARIO)
VALUES('Pedro Henrique Cacique Braga','cacique','123456',1);

INSERT
INTO PROJETO.USUARIO(NOME_USUARIO, LOGIN_USUARIO, SENHA_USUARIO, ID_TIPO_USUARIO)
VALUES('Usuário','usuario','usuario',1);

INSERT
INTO PROJETO.USUARIO(NOME_USUARIO, LOGIN_USUARIO, SENHA_USUARIO, ID_TIPO_USUARIO)
VALUES('Administrador','admin','admin',2);

-- INSERT LIVROS E SEUS RESPECTIVOS AUTORES

INSERT
INTO PROJETO.LIVRO(ID_AUTOR,NOME_LIVRO)
VALUES (1,'As Aventuras de Sherlock Holmes');

INSERT
INTO PROJETO.LIVRO(ID_AUTOR,NOME_LIVRO)
VALUES (2,'O Nevoeiro');

INSERT
INTO PROJETO.LIVRO(ID_AUTOR,NOME_LIVRO)
VALUES (2,'O Iluminado');

INSERT
INTO PROJETO.LIVRO(ID_AUTOR,NOME_LIVRO)
VALUES (3,'O Alquimista');

INSERT
INTO PROJETO.LIVRO(ID_AUTOR,NOME_LIVRO)
VALUES (4,'O Último Reino');

INSERT
INTO PROJETO.LIVRO(ID_AUTOR,NOME_LIVRO)
VALUES (5,'O Chamado de Cthulhu');

INSERT
INTO PROJETO.LIVRO(ID_AUTOR,NOME_LIVRO)
VALUES (6,'Eu, Robô');

--INSERT EMPRESTIMO

INSERT
INTO PROJETO.EMPRESTIMO(ID_LIVRO, ID_USUARIO, DATA_EMPRESTIMO)
VALUES(1,2,'2016-05-20');

INSERT
INTO PROJETO.EMPRESTIMO(ID_LIVRO, ID_USUARIO, DATA_EMPRESTIMO)
VALUES(3,4,'2016-04-11');

INSERT
INTO PROJETO.EMPRESTIMO(ID_LIVRO, ID_USUARIO, DATA_EMPRESTIMO)
VALUES(6,1,'2016-05-18');

INSERT
INTO PROJETO.EMPRESTIMO(ID_LIVRO, ID_USUARIO, DATA_EMPRESTIMO)
VALUES(2,5,'2016-05-22');